/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Empty: typeof import('./src/components/empty.vue')['default']
    NavigationBar: typeof import('./src/components/navigationBar.vue')['default']
    Password: typeof import('./src/components/password/index.ts')['default']
    PasswordPopup: typeof import('./src/components/password/passwordPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwipeAction: typeof import('./src/components/swipeAction.vue')['default']
    TermAndPrivacy: typeof import('./src/components/termAndPrivacy.vue')['default']
    TitleBar: typeof import('./src/components/titleBar.vue')['default']
    TransferPopup: typeof import('./src/components/transferPopup.vue')['default']
    VersionPopup: typeof import('./src/components/versionPopup.vue')['default']
    WalletPopup: typeof import('./src/components/walletPopup.vue')['default']
    WalletTabbar: typeof import('./src/components/walletTabbar.vue')['default']
  }
}
