/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tool: typeof import('./src/components/waterfall/tool.ts')['default']
    Type: typeof import('./src/components/waterfall/type.ts')['default']
    Waterfall: typeof import('./src/components/waterfall/waterfall.vue')['default']
  }
}
